import pandas as pd
import os
try:
    from sklearn.metrics import classification_report
except ImportError:
    print("❌ Error: scikit-learn is not installed. Please run: pip install scikit-learn")
    classification_report = None

def calculate_thesis_metrics():
    file_path = "thesis_final_benchmark.csv"
    
    if not os.path.exists(file_path):
        print(f"❌ Error: Could not find {file_path}.")
        return

    print("-> Loading Filtered Benchmark Dataset...\n")
    df = pd.read_csv(file_path)

    # Clean up strings
    df['human_ground_truth'] = df['human_ground_truth'].fillna('').astype(str).str.strip().str.upper()
    df['model_label'] = df['model_label'].astype(str).str.strip().str.upper()
    df['agent_final_decision'] = df['agent_final_decision'].astype(str).str.strip().str.upper()

    total_records = len(df)

    # --- THE TRANSLATION MAPPING ---
    def map_agent_label(row):
        model_label = row['model_label']
        decision = row['agent_final_decision']
        
        if decision == 'CORRECT':
            return model_label
        elif decision == 'FALSE POSITIVE':
            return 'NORMAL'
        elif decision == 'FALSE NEGATIVE':
            return 'OFFENSIVE' # Catch-all for toxic false negatives
        else:
            return model_label # Fallback

    df['agent_predicted_label'] = df.apply(map_agent_label, axis=1)

    # ---------------------------------------------------------
    # PART 1: METRICS THAT DO NOT REQUIRE HUMAN LABELS
    # ---------------------------------------------------------
    ai_agreed = len(df[df['model_label'] == df['agent_predicted_label']])
    agreement_rate = (ai_agreed / total_records) * 100

    df['processing_time_ms'] = pd.to_numeric(df['processing_time_ms'], errors='coerce')
    df['agent_latency_seconds'] = pd.to_numeric(df['agent_latency_seconds'], errors='coerce')

    avg_t1_ms = df['processing_time_ms'].mean()
    avg_t2_sec = df['agent_latency_seconds'].mean()
    avg_t2_ms = avg_t2_sec * 1000

    slowdown_factor = (avg_t2_ms / avg_t1_ms) if avg_t1_ms > 0 else 0

    print("=====================================================================")
    print("             THESIS METRICS: PERFORMANCE BENCHMARK                   ")
    print("=====================================================================")
    print(f"Total Dataset Size:           {total_records} records")
    print(f"Model Agreement Rate:         {agreement_rate:.1f}%")
    
    print("-" * 69)
    print("1. LATENCY / SPEED TRADE-OFF (NORMALIZED)")
    print(f"   Tier-1 Average (Static):      {avg_t1_ms:.2f} ms")
    print(f"   Tier-2 Average (Agent):       {avg_t2_ms:.2f} ms ({avg_t2_sec:.2f} seconds)")
    print(f"   Intelligence Overhead:        {slowdown_factor:.1f}x slower than Tier-1")
    print("-" * 69)

    # ---------------------------------------------------------
    # PART 2: METRICS THAT REQUIRE HUMAN LABELS
    # ---------------------------------------------------------
    labeled_df = df[df['human_ground_truth'] != '']
    total_labeled = len(labeled_df)

    if total_labeled == 0:
        return

    distilbert_correct = len(labeled_df[labeled_df['model_label'] == labeled_df['human_ground_truth']])
    agent_correct = len(labeled_df[labeled_df['agent_predicted_label'] == labeled_df['human_ground_truth']])

    distilbert_acc = (distilbert_correct / total_labeled) * 100
    agent_acc = (agent_correct / total_labeled) * 100

    # Label Noise (False Positive) Reduction
    distilbert_fps = labeled_df[
        (labeled_df['model_label'].isin(['HATE', 'OFFENSIVE'])) & 
        (labeled_df['human_ground_truth'] == 'NORMAL')
    ]
    total_noise_generated = len(distilbert_fps)
    agent_fixed_fps = distilbert_fps[distilbert_fps['agent_predicted_label'] == 'NORMAL']
    total_noise_cleaned = len(agent_fixed_fps)

    noise_reduction_rate = (total_noise_cleaned / total_noise_generated * 100) if total_noise_generated > 0 else 0

    print("2. OVERALL ACCURACY (Verified against Human Ground Truth)")
    print(f"   Manual Sample Size:        n = {total_labeled}")
    print(f"   Tier-1 (DistilBERT):       {distilbert_acc:.1f}% ({distilbert_correct}/{total_labeled})")
    print(f"   Tier-2 (Agent Overlay):    {agent_acc:.1f}% ({agent_correct}/{total_labeled})")
    print("-" * 69)
    
    print("3. LABEL NOISE (FALSE POSITIVE) RESOLUTION")
    print(f"   False Positives Generated by Tier-1:  {total_noise_generated}")
    print(f"   False Positives Corrected by Tier-2:  {total_noise_cleaned}")
    print(f"   Noise Reduction Effectiveness:        {noise_reduction_rate:.1f}%")
    print("-" * 69)

    # ---------------------------------------------------------
    # PART 3: ADVANCED CLASSIFICATION METRICS (Precision, Recall, F1)
    # ---------------------------------------------------------
    if classification_report:
        t1_dict = classification_report(labeled_df['human_ground_truth'], labeled_df['model_label'], output_dict=True, zero_division=0)
        t2_dict = classification_report(labeled_df['human_ground_truth'], labeled_df['agent_predicted_label'], output_dict=True, zero_division=0)

        classes = ['NORMAL', 'OFFENSIVE', 'HATE']

        print("4. ADVANCED CLASSIFICATION METRICS (Tier-1 vs Tier-2)")
        print(f"   {'Class':<12} | {'Precision (T1/T2)':<17} | {'Recall (T1/T2)':<15} | {'F1-Score (T1/T2)'}")
        print("   " + "-" * 66)
        
        for cls in classes:
            if cls in t1_dict and cls in t2_dict:
                p1, p2 = t1_dict[cls]['precision'], t2_dict[cls]['precision']
                r1, r2 = t1_dict[cls]['recall'], t2_dict[cls]['recall']
                f1, f2 = t1_dict[cls]['f1-score'], t2_dict[cls]['f1-score']
                print(f"   {cls:<12} | {p1:.2f} / {p2:.2f}         | {r1:.2f} / {r2:.2f}       | {f1:.2f} / {f2:.2f}")

        # Macro avg
        if 'macro avg' in t1_dict and 'macro avg' in t2_dict:
            p1, p2 = t1_dict['macro avg']['precision'], t2_dict['macro avg']['precision']
            r1, r2 = t1_dict['macro avg']['recall'], t2_dict['macro avg']['recall']
            f1, f2 = t1_dict['macro avg']['f1-score'], t2_dict['macro avg']['f1-score']
            print("   " + "-" * 66)
            print(f"   {'Macro Avg':<12} | {p1:.2f} / {p2:.2f}         | {r1:.2f} / {r2:.2f}       | {f1:.2f} / {f2:.2f}")

    print("=====================================================================\n")
# ---------------------------------------------------------
    # PART 5: TRIPARTITE AGREEMENT (ALL 3 JUDGES)
    # ---------------------------------------------------------
    print("5. TRIPARTITE AGREEMENT & INTER-RATER OVERLAP")
    
    # 1. All three agree exactly
    unanimous = labeled_df[
        (labeled_df['model_label'] == labeled_df['agent_predicted_label']) & 
        (labeled_df['agent_predicted_label'] == labeled_df['human_ground_truth'])
    ]
    unanimous_rate = (len(unanimous) / total_labeled) * 100

    # 2. Agent & Human agree, but Static failed (The "Contextual Rescue")
    agent_human_only = labeled_df[
        (labeled_df['agent_predicted_label'] == labeled_df['human_ground_truth']) & 
        (labeled_df['model_label'] != labeled_df['human_ground_truth'])
    ]
    agent_human_rate = (len(agent_human_only) / total_labeled) * 100

    # 3. Both AI models failed the Human check
    ai_failed = labeled_df[
        (labeled_df['model_label'] != labeled_df['human_ground_truth']) & 
        (labeled_df['agent_predicted_label'] != labeled_df['human_ground_truth'])
    ]
    ai_failed_rate = (len(ai_failed) / total_labeled) * 100

    print(f"   Unanimous Agreement (All 3 Match):    {unanimous_rate:.1f}% ({len(unanimous)} records)")
    print(f"   Agent & Human Match (Static Failed):  {agent_human_rate:.1f}% ({len(agent_human_only)} records)")
    print(f"   Both AI Models Failed (vs Human):     {ai_failed_rate:.1f}% ({len(ai_failed)} records)")
    print("=====================================================================\n")
if __name__ == "__main__":
    calculate_thesis_metrics()